---
- name: Cluster | Include tasks {{ protocol }} cluster
  include_tasks: '{{ protocol }}.yaml'
  when: profile == "standalone-ha"

- name: Cluster | Include jvm tunnig
  include_tasks: jvm.yaml

- name: Cluster | Include SO tunning
  include_tasks: so.yaml

- name: Cluster | Include tasks to proxy
  include_tasks: proxy.yaml
  when: profile == "standalone-ha"
